// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct CommentData {
  string commenter;
  string body;
}

library Comment {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "app", name: "Comment", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74626170700000000000000000000000436f6d6d656e74000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000200000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint64, uint64)
  Schema constant _keySchema = Schema.wrap(0x0010020007070000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (string, string)
  Schema constant _valueSchema = Schema.wrap(0x00000002c5c50000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "articleId";
    keyNames[1] = "commentSeqId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "commenter";
    fieldNames[1] = "body";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get commenter.
   */
  function getCommenter(uint64 articleId, uint64 commentSeqId) internal view returns (string memory commenter) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get commenter.
   */
  function _getCommenter(uint64 articleId, uint64 commentSeqId) internal view returns (string memory commenter) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set commenter.
   */
  function setCommenter(uint64 articleId, uint64 commentSeqId, string memory commenter) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((commenter)));
  }

  /**
   * @notice Set commenter.
   */
  function _setCommenter(uint64 articleId, uint64 commentSeqId, string memory commenter) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((commenter)));
  }

  /**
   * @notice Get the length of commenter.
   */
  function lengthCommenter(uint64 articleId, uint64 commentSeqId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of commenter.
   */
  function _lengthCommenter(uint64 articleId, uint64 commentSeqId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of commenter.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemCommenter(
    uint64 articleId,
    uint64 commentSeqId,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of commenter.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemCommenter(
    uint64 articleId,
    uint64 commentSeqId,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to commenter.
   */
  function pushCommenter(uint64 articleId, uint64 commentSeqId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to commenter.
   */
  function _pushCommenter(uint64 articleId, uint64 commentSeqId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from commenter.
   */
  function popCommenter(uint64 articleId, uint64 commentSeqId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from commenter.
   */
  function _popCommenter(uint64 articleId, uint64 commentSeqId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of commenter at `_index`.
   */
  function updateCommenter(uint64 articleId, uint64 commentSeqId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of commenter at `_index`.
   */
  function _updateCommenter(uint64 articleId, uint64 commentSeqId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get body.
   */
  function getBody(uint64 articleId, uint64 commentSeqId) internal view returns (string memory body) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 1);
    return (string(_blob));
  }

  /**
   * @notice Get body.
   */
  function _getBody(uint64 articleId, uint64 commentSeqId) internal view returns (string memory body) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 1);
    return (string(_blob));
  }

  /**
   * @notice Set body.
   */
  function setBody(uint64 articleId, uint64 commentSeqId, string memory body) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 1, bytes((body)));
  }

  /**
   * @notice Set body.
   */
  function _setBody(uint64 articleId, uint64 commentSeqId, string memory body) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.setDynamicField(_tableId, _keyTuple, 1, bytes((body)));
  }

  /**
   * @notice Get the length of body.
   */
  function lengthBody(uint64 articleId, uint64 commentSeqId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 1);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of body.
   */
  function _lengthBody(uint64 articleId, uint64 commentSeqId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 1);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of body.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemBody(uint64 articleId, uint64 commentSeqId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 1, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of body.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemBody(uint64 articleId, uint64 commentSeqId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 1, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to body.
   */
  function pushBody(uint64 articleId, uint64 commentSeqId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 1, bytes((_slice)));
  }

  /**
   * @notice Push a slice to body.
   */
  function _pushBody(uint64 articleId, uint64 commentSeqId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 1, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from body.
   */
  function popBody(uint64 articleId, uint64 commentSeqId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 1, 1);
  }

  /**
   * @notice Pop a slice from body.
   */
  function _popBody(uint64 articleId, uint64 commentSeqId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 1, 1);
  }

  /**
   * @notice Update a slice of body at `_index`.
   */
  function updateBody(uint64 articleId, uint64 commentSeqId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 1, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of body at `_index`.
   */
  function _updateBody(uint64 articleId, uint64 commentSeqId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 1, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(uint64 articleId, uint64 commentSeqId) internal view returns (CommentData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint64 articleId, uint64 commentSeqId) internal view returns (CommentData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(uint64 articleId, uint64 commentSeqId, string memory commenter, string memory body) internal {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(commenter, body);
    bytes memory _dynamicData = encodeDynamic(commenter, body);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(uint64 articleId, uint64 commentSeqId, string memory commenter, string memory body) internal {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(commenter, body);
    bytes memory _dynamicData = encodeDynamic(commenter, body);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint64 articleId, uint64 commentSeqId, CommentData memory _table) internal {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(_table.commenter, _table.body);
    bytes memory _dynamicData = encodeDynamic(_table.commenter, _table.body);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint64 articleId, uint64 commentSeqId, CommentData memory _table) internal {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(_table.commenter, _table.body);
    bytes memory _dynamicData = encodeDynamic(_table.commenter, _table.body);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory commenter, string memory body) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    commenter = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));

    _start = _end;
    unchecked {
      _end += _encodedLengths.atIndex(1);
    }
    body = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   *
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (CommentData memory _table) {
    (_table.commenter, _table.body) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint64 articleId, uint64 commentSeqId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint64 articleId, uint64 commentSeqId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(
    string memory commenter,
    string memory body
  ) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(commenter).length, bytes(body).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory commenter, string memory body) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((commenter)), bytes((body)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    string memory commenter,
    string memory body
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(commenter, body);
    bytes memory _dynamicData = encodeDynamic(commenter, body);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint64 articleId, uint64 commentSeqId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(articleId));
    _keyTuple[1] = bytes32(uint256(commentSeqId));

    return _keyTuple;
  }
}
