// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library ShipItemMountingPosition {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "app", name: "ShipItemMounting", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74626170700000000000000000000000536869704974656d4d6f756e74696e67);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0001010001000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint32, uint8)
  Schema constant _keySchema = Schema.wrap(0x0005020003000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8)
  Schema constant _valueSchema = Schema.wrap(0x0001010000000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "shipItemMountingPositionIdItemId";
    keyNames[1] = "shipItemMountingPositionIdMountingPosition";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "equipmentCapacity";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get equipmentCapacity.
   */
  function getEquipmentCapacity(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition
  ) internal view returns (uint8 equipmentCapacity) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get equipmentCapacity.
   */
  function _getEquipmentCapacity(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition
  ) internal view returns (uint8 equipmentCapacity) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get equipmentCapacity.
   */
  function get(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition
  ) internal view returns (uint8 equipmentCapacity) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get equipmentCapacity.
   */
  function _get(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition
  ) internal view returns (uint8 equipmentCapacity) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set equipmentCapacity.
   */
  function setEquipmentCapacity(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition,
    uint8 equipmentCapacity
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((equipmentCapacity)), _fieldLayout);
  }

  /**
   * @notice Set equipmentCapacity.
   */
  function _setEquipmentCapacity(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition,
    uint8 equipmentCapacity
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((equipmentCapacity)), _fieldLayout);
  }

  /**
   * @notice Set equipmentCapacity.
   */
  function set(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition,
    uint8 equipmentCapacity
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((equipmentCapacity)), _fieldLayout);
  }

  /**
   * @notice Set equipmentCapacity.
   */
  function _set(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition,
    uint8 equipmentCapacity
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((equipmentCapacity)), _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint8 equipmentCapacity) internal pure returns (bytes memory) {
    return abi.encodePacked(equipmentCapacity);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(uint8 equipmentCapacity) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(equipmentCapacity);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(
    uint32 shipItemMountingPositionIdItemId,
    uint8 shipItemMountingPositionIdMountingPosition
  ) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(shipItemMountingPositionIdItemId));
    _keyTuple[1] = bytes32(uint256(shipItemMountingPositionIdMountingPosition));

    return _keyTuple;
  }
}
