// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Terrain, TerrainData } from "./tables/Terrain.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { Counter } from "./tables/Counter.sol";
import { Map, MapData } from "./tables/Map.sol";
import { MapLocation, MapLocationData } from "./tables/MapLocation.sol";
