// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEnergyTokenSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEnergyTokenSystem {
  function app__energyTokenCreate(address tokenAddress, uint256 faucetDropAmount, uint64 faucetDropInterval) external;

  function app__energyTokenUpdate(address tokenAddress, uint256 faucetDropAmount, uint64 faucetDropInterval) external;
}
