// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IExperienceTableSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IExperienceTableSystem {
  function app__experienceTableCreate(bool reservedBool1) external;

  function app__experienceTableUpdate(bool reservedBool1) external;
}
