// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IItemToShipAttributesSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemToShipAttributesSystem {
  function app__itemToShipAttributesCreate(
    uint32 itemId,
    uint32 denominator,
    uint32 attackNumerator,
    uint32 protectionNumerator,
    uint32 speedNumerator,
    uint32 healthNumerator
  ) external;

  function app__itemToShipAttributesUpdate(
    uint32 itemId,
    uint32 denominator,
    uint32 attackNumerator,
    uint32 protectionNumerator,
    uint32 speedNumerator,
    uint32 healthNumerator
  ) external;
}
