// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TwoRostersLocationUpdateParams } from "../../systems/TwoRostersLocationUpdateParams.sol";

/**
 * @title IRosterShipTransferSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRosterShipTransferSystem {
  function app__rosterTransferShip(
    uint256 playerId,
    uint32 sequenceNumber,
    uint256 shipId,
    uint256 toRosterPlayerId,
    uint32 toRosterSequenceNumber,
    uint64 toPosition,
    TwoRostersLocationUpdateParams memory locationUpdateParams
  ) external;

  function app__rosterTransferMultiShips(
    uint256 playerId,
    uint32 sequenceNumber,
    uint256[] memory shipIds,
    uint256 toRosterPlayerId,
    uint32 toRosterSequenceNumber,
    uint64 toPosition,
    TwoRostersLocationUpdateParams memory locationUpdateParams
  ) external;
}
