// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IShipBattleServiceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IShipBattleServiceSystem {
  function app__shipBattleServiceInitiateBattleAndAutoPlayTillEnd(
    uint256 playerId,
    int32 initiatorCoordinatesX,
    int32 initiatorCoordinatesY,
    int32 responderCoordinatesX,
    int32 responderCoordinatesY
  ) external;

  function app__shipBattleServiceAutoPlayTillEnd(uint256 shipBattleId, uint256 playerId) external;
}
