// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IShipBattleInitiateSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IShipBattleInitiateSystem {
  function app__initiateShipBattle(
    uint256 playerId,
    uint256 initiatorRosterPlayerId,
    uint32 initiatorRosterSequenceNumber,
    uint256 responderRosterPlayerId,
    uint32 responderRosterSequenceNumber,
    uint32 initiatorCoordinatesX,
    uint32 initiatorCoordinatesY,
    uint16 updatedInitiatorSailSeg,
    uint32 responderCoordinatesX,
    uint32 responderCoordinatesY,
    uint16 updatedResponderSailSeg
  ) external returns (uint256);
}
