// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IShipBattleSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IShipBattleSystem {
  function app__shipBattleInitiateBattle(
    uint256 playerId,
    uint256 initiatorRosterPlayerId,
    uint32 initiatorRosterSequenceNumber,
    uint256 responderRosterPlayerId,
    uint32 responderRosterSequenceNumber,
    int32 initiatorCoordinatesX,
    int32 initiatorCoordinatesY,
    int32 responderCoordinatesX,
    int32 responderCoordinatesY
  ) external;

  function app__shipBattleMakeMove(uint256 id, uint8 attackerCommand) external;
}
