// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITerrainSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITerrainSystem {
  function app__terrainCreate(
    uint32 x,
    uint32 y,
    string memory terrainType,
    uint8[] memory foo,
    bytes memory bar
  ) external;

  function app__terrainUpdate(
    uint32 x,
    uint32 y,
    string memory terrainType,
    uint8[] memory foo,
    bytes memory bar
  ) external;
}
