// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

library BattleStatus {
  uint8 constant IN_PROGRESS = 0;
  uint8 constant ENDED = 1;
  uint8 constant LOOTED = 2;
}

