// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

struct ItemToShipAttributesCreated {
  uint32 itemId;
  uint32 denominator;
  uint32 attackNumerator;
  uint32 protectionNumerator;
  uint32 speedNumerator;
  uint32 healthNumerator;
}

struct ItemToShipAttributesUpdated {
  uint32 itemId;
  uint32 denominator;
  uint32 attackNumerator;
  uint32 protectionNumerator;
  uint32 speedNumerator;
  uint32 healthNumerator;
}

