// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

struct ItemCreationCreated {
  /**
   * @dev The SkillType of the ItemCreationId.
   */
  uint8 skillType;
  /**
   * @dev The ItemId of the ItemCreationId.
   */
  uint32 itemId;
  uint16 requirementsLevel;
  uint32 baseQuantity;
  uint32 baseExperience;
  uint64 baseCreationTime;
  uint64 energyCost;
  uint16 successRate;
  uint32 resourceCost;
}

struct ItemCreationUpdated {
  /**
   * @dev The SkillType of the ItemCreationId.
   */
  uint8 skillType;
  /**
   * @dev The ItemId of the ItemCreationId.
   */
  uint32 itemId;
  uint16 requirementsLevel;
  uint32 baseQuantity;
  uint32 baseExperience;
  uint64 baseCreationTime;
  uint64 energyCost;
  uint16 successRate;
  uint32 resourceCost;
}

