// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Map, MapData } from "../codegen/index.sol";
import { MapIslandClaimed, IslandResourcesGathered } from "./MapEvents.sol";
import { MapClaimIslandLogic } from "./MapClaimIslandLogic.sol";
import { MapGatherIslandResourcesLogic } from "./MapGatherIslandResourcesLogic.sol";
import { ItemIdQuantityPair } from "./ItemIdQuantityPair.sol";
import { SystemRegistry } from "@latticexyz/world/src/codegen/tables/SystemRegistry.sol";
import { AccessControl } from "@latticexyz/world/src/AccessControl.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";

library MapAggregateLib {
  event MapIslandClaimedEvent(int32 coordinatesX, int32 coordinatesY, uint256 claimedBy, uint64 claimedAt);

  event IslandResourcesGatheredEvent(uint256 playerId, uint64 gatheredAt, int32 coordinatesX, int32 coordinatesY);

  function _requireOwner() internal view {
    AccessControl.requireOwner(SystemRegistry.get(address(this)), WorldContextConsumerLib._msgSender());
  }

  function claimIsland(int32 coordinatesX, int32 coordinatesY, uint256 claimedBy, uint64 claimedAt) internal {
    MapData memory mapData = Map.get();
    require(
      !(mapData.width == uint32(0) && mapData.height == uint32(0)),
      "Map does not exist"
    );
    MapIslandClaimed memory mapIslandClaimed = MapClaimIslandLogic.verify(coordinatesX, coordinatesY, claimedBy, claimedAt, mapData);
    emit MapIslandClaimedEvent(mapIslandClaimed.coordinatesX, mapIslandClaimed.coordinatesY, mapIslandClaimed.claimedBy, mapIslandClaimed.claimedAt);
    MapData memory updatedMapData = MapClaimIslandLogic.mutate(mapIslandClaimed, mapData);
    Map.set(updatedMapData);
  }

  function gatherIslandResources(uint256 playerId, int32 coordinatesX, int32 coordinatesY) internal returns (ItemIdQuantityPair[] memory) {
    MapData memory mapData = Map.get();
    require(
      !(mapData.width == uint32(0) && mapData.height == uint32(0)),
      "Map does not exist"
    );
    IslandResourcesGathered memory islandResourcesGathered = MapGatherIslandResourcesLogic.verify(playerId, coordinatesX, coordinatesY, mapData);
    emit IslandResourcesGatheredEvent(islandResourcesGathered.playerId, islandResourcesGathered.gatheredAt, islandResourcesGathered.coordinatesX, islandResourcesGathered.coordinatesY);
    (ItemIdQuantityPair[] memory result, MapData memory updatedMapData) = MapGatherIslandResourcesLogic.mutate(islandResourcesGathered, mapData);
    Map.set(updatedMapData);
    return result;
  }

}
