// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { System } from "@latticexyz/world/src/System.sol";
import { Map, MapData } from "../codegen/index.sol";
import { MapCreated, MapUpdated, IslandAdded, MultiIslandsAdded, IslandResourcesAirdropped } from "./MapEvents.sol";
import { MapCreateLogic } from "./MapCreateLogic.sol";
import { MapUpdateLogic } from "./MapUpdateLogic.sol";
import { MapAddIslandLogic } from "./MapAddIslandLogic.sol";
import { MapAddMultiIslandsLogic } from "./MapAddMultiIslandsLogic.sol";
import { MapAirdropLogic } from "./MapAirdropLogic.sol";
import { ItemIdQuantityPair } from "./ItemIdQuantityPair.sol";
import { Coordinates } from "./Coordinates.sol";
import { SystemRegistry } from "@latticexyz/world/src/codegen/tables/SystemRegistry.sol";
import { NamespaceOwner } from "@latticexyz/world/src/codegen/tables/NamespaceOwner.sol";
import { ResourceId, WorldResourceIdInstance } from "@latticexyz/world/src/WorldResourceId.sol";
import { IAppSystemErrors } from "./IAppSystemErrors.sol";

contract MapSystem is System, IAppSystemErrors {
  using WorldResourceIdInstance for ResourceId;

  event MapCreatedEvent(bool existing, bool islandClaimWhitelistEnabled);

  event MapUpdatedEvent(bool existing, bool islandClaimWhitelistEnabled);

  event IslandAddedEvent(uint32 coordinatesX, uint32 coordinatesY);

  event MultiIslandsAddedEvent(uint32[] resourceItemIds, uint32 resourceSubtotal);

  event IslandResourcesAirdroppedEvent(uint32 coordinatesX, uint32 coordinatesY, uint32[] resourcesItemIds, uint32[] resourcesQuantities);

  function _requireNamespaceOwner() internal view {
    ResourceId _thisSystemId = SystemRegistry.get(address(this));
    address _thisNamespaceOwner = NamespaceOwner.get(_thisSystemId.getNamespaceId());
    if (_thisNamespaceOwner != _msgSender()) {
      revert RequireNamespaceOwner(_msgSender(), _thisNamespaceOwner);
    }
  }

  function mapCreate(bool existing, bool islandClaimWhitelistEnabled) public {
    _requireNamespaceOwner();
    MapData memory mapData = Map.get();
    if (!(mapData.existing == false && mapData.islandClaimWhitelistEnabled == false)) {
      revert MapAlreadyExists();
    }
    MapCreated memory mapCreated = MapCreateLogic.verify(existing, islandClaimWhitelistEnabled);
    emit MapCreatedEvent(mapCreated.existing, mapCreated.islandClaimWhitelistEnabled);
    MapData memory newMapData = MapCreateLogic.mutate(mapCreated);
    Map.set(newMapData);
  }

  function mapUpdate(bool existing, bool islandClaimWhitelistEnabled) public {
    _requireNamespaceOwner();
    MapData memory mapData = Map.get();
    if (mapData.existing == false && mapData.islandClaimWhitelistEnabled == false) {
      revert MapDoesNotExist();
    }
    MapUpdated memory mapUpdated = MapUpdateLogic.verify(existing, islandClaimWhitelistEnabled, mapData);
    emit MapUpdatedEvent(mapUpdated.existing, mapUpdated.islandClaimWhitelistEnabled);
    MapData memory updatedMapData = MapUpdateLogic.mutate(mapUpdated, mapData);
    Map.set(updatedMapData);
  }

  function mapAddIsland(uint32 coordinatesX, uint32 coordinatesY, ItemIdQuantityPair[] memory resources) public {
    _requireNamespaceOwner();
    MapData memory mapData = Map.get();
    if (mapData.existing == false && mapData.islandClaimWhitelistEnabled == false) {
      revert MapDoesNotExist();
    }
    IslandAdded memory islandAdded = MapAddIslandLogic.verify(coordinatesX, coordinatesY, resources, mapData);
    emit IslandAddedEvent(islandAdded.coordinatesX, islandAdded.coordinatesY);
    MapData memory updatedMapData = MapAddIslandLogic.mutate(islandAdded, mapData);
    Map.set(updatedMapData);
  }

  function mapAddMultiIslands(Coordinates[] memory coordinates, uint32[] memory resourceItemIds, uint32 resourceSubtotal) public {
    _requireNamespaceOwner();
    MapData memory mapData = Map.get();
    if (mapData.existing == false && mapData.islandClaimWhitelistEnabled == false) {
      revert MapDoesNotExist();
    }
    MultiIslandsAdded memory multiIslandsAdded = MapAddMultiIslandsLogic.verify(coordinates, resourceItemIds, resourceSubtotal, mapData);
    emit MultiIslandsAddedEvent(multiIslandsAdded.resourceItemIds, multiIslandsAdded.resourceSubtotal);
    MapData memory updatedMapData = MapAddMultiIslandsLogic.mutate(multiIslandsAdded, mapData);
    Map.set(updatedMapData);
  }

  function mapAirdrop(uint32 coordinatesX, uint32 coordinatesY, uint32[] memory resourcesItemIds, uint32[] memory resourcesQuantities) public {
    _requireNamespaceOwner();
    MapData memory mapData = Map.get();
    if (mapData.existing == false && mapData.islandClaimWhitelistEnabled == false) {
      revert MapDoesNotExist();
    }
    IslandResourcesAirdropped memory islandResourcesAirdropped = MapAirdropLogic.verify(coordinatesX, coordinatesY, resourcesItemIds, resourcesQuantities, mapData);
    emit IslandResourcesAirdroppedEvent(islandResourcesAirdropped.coordinatesX, islandResourcesAirdropped.coordinatesY, islandResourcesAirdropped.resourcesItemIds, islandResourcesAirdropped.resourcesQuantities);
    MapData memory updatedMapData = MapAirdropLogic.mutate(islandResourcesAirdropped, mapData);
    Map.set(updatedMapData);
  }

}
