// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { System } from "@latticexyz/world/src/System.sol";
import { Player, PlayerData, PlayerIdGenerator } from "../codegen/index.sol";

contract PlayerSystem is System {
}
