// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

struct RosterCreated {
  uint256 playerId;
  uint32 sequenceNumber;
}

struct EnvironmentRosterCreated {
  uint256 playerId;
  uint32 sequenceNumber;
  int32 coordinatesX;
  int32 coordinatesY;
  uint32 shipResourceQuantity;
  uint32 shipBaseResourceQuantity;
  uint32 baseExperience;
}

struct RosterShipAdded {
  uint256 playerId;
  uint32 sequenceNumber;
  uint256 shipId;
  uint64 position;
}

struct RosterSetSail {
  uint256 playerId;
  uint32 sequenceNumber;
  int32 targetCoordinatesX;
  int32 targetCoordinatesY;
  uint64 sailDuration;
  uint64 setSailAt;
  int32 updatedCoordinatesX;
  int32 updatedCoordinatesY;
  uint64 energyCost;
}

struct RosterShipsPositionAdjusted {
  uint256 playerId;
  uint32 sequenceNumber;
  uint64[] positions;
  uint256[] shipIds;
}

struct RosterShipTransferred {
  uint256 playerId;
  uint32 sequenceNumber;
  uint256 shipId;
  uint256 toRosterPlayerId;
  uint32 toRosterSequenceNumber;
  uint64 toPosition;
  uint64 transferredAt;
}

struct RosterShipInventoryTransferred {
  uint256 playerId;
  uint32 sequenceNumber;
  uint256 fromShipId;
  uint256 toShipId;
}

struct RosterShipInventoryTakenOut {
  uint256 playerId;
  uint32 sequenceNumber;
  uint256 shipId;
  int32 updatedCoordinatesX;
  int32 updatedCoordinatesY;
}

struct RosterShipInventoryPutIn {
  uint256 playerId;
  uint32 sequenceNumber;
  uint256 shipId;
  int32 updatedCoordinatesX;
  int32 updatedCoordinatesY;
}

