// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemIdQuantityPair } from "./ItemIdQuantityPair.sol";

struct RosterCleanUpBattleResult {
  uint256[] winnerRemainingShipIds;
  uint32 winnerNewSpeed;
  uint256[] loserDestroyedShipIds;
  ItemIdQuantityPair[] loot;
}

