// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

library RosterStatus {
  uint8 constant UNUSED = 0;
  uint8 constant AT_ANCHOR = 255;
  uint8 constant UNDERWAY = 1;
  uint8 constant IN_BATTLE = 2;
  uint8 constant DESTROYED = 3;
}

