// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

library RosterStatus {
  uint8 constant UNUSED = 0;
  uint8 constant AT_ANCHOR = 255;
  uint8 constant UNDERWAY = 1;
  uint8 constant IN_BATTLE = 2;
  uint8 constant DESTROYED = 3;

  function isValid(uint8 v) internal pure returns (bool) {
    return v == UNUSED || v == AT_ANCHOR || v == UNDERWAY || v == IN_BATTLE || v == DESTROYED;
  }

  function allValidValues() internal pure returns (uint8[] memory) {
    uint8[] memory values = new uint8[](5);
    values[0] = UNUSED;
    values[1] = AT_ANCHOR;
    values[2] = UNDERWAY;
    values[3] = IN_BATTLE;
    values[4] = DESTROYED;
    return values;
  }
}

