// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Roster, RosterData } from "../codegen/index.sol";
import { RosterCreated, RosterShipAdded } from "./RosterEvents.sol";
import { RosterCreateLogic } from "./RosterCreateLogic.sol";
import { RosterAddShipLogic } from "./RosterAddShipLogic.sol";

library RosterAggregateLib {
  event RosterCreatedEvent(uint256 indexed playerId, uint32 indexed sequenceNumber);

  event RosterShipAddedEvent(uint256 indexed playerId, uint32 indexed sequenceNumber, uint256 shipId, uint64 position);

  function rosterCreate(uint256 playerId, uint32 sequenceNumber) internal returns (uint256, uint32, RosterData memory) {
    RosterData memory rosterData = Roster.get(playerId, sequenceNumber);
    require(
      !(rosterData.status == 0 && rosterData.speed == 0 && rosterData.coordinatesUpdatedAt == 0 && rosterData.sailDuration == 0 && rosterData.setSailAt == 0 && rosterData.shipBattleId == 0 && rosterData.environmentOwned == false && rosterData.baseExperience == 0 && rosterData.shipIds.length == 0),
      "Roster does not exist"
    );
    RosterCreated memory rosterCreated = RosterCreateLogic.verify(playerId, sequenceNumber, rosterData);
    rosterCreated.playerId = playerId;
    rosterCreated.sequenceNumber = sequenceNumber;
    emit RosterCreatedEvent(rosterCreated.playerId, rosterCreated.sequenceNumber);
    RosterData memory updatedRosterData = RosterCreateLogic.mutate(rosterCreated, rosterData);
    Roster.set(playerId, sequenceNumber, updatedRosterData);
    return (playerId, sequenceNumber, updatedRosterData);
  }

  function rosterAddShip(uint256 playerId, uint32 sequenceNumber, uint256 shipId, uint64 position) internal {
    RosterData memory rosterData = Roster.get(playerId, sequenceNumber);
    require(
      !(rosterData.status == 0 && rosterData.speed == 0 && rosterData.coordinatesUpdatedAt == 0 && rosterData.sailDuration == 0 && rosterData.setSailAt == 0 && rosterData.shipBattleId == 0 && rosterData.environmentOwned == false && rosterData.baseExperience == 0 && rosterData.shipIds.length == 0),
      "Roster does not exist"
    );
    RosterShipAdded memory rosterShipAdded = RosterAddShipLogic.verify(playerId, sequenceNumber, shipId, position, rosterData);
    rosterShipAdded.playerId = playerId;
    rosterShipAdded.sequenceNumber = sequenceNumber;
    emit RosterShipAddedEvent(rosterShipAdded.playerId, rosterShipAdded.sequenceNumber, rosterShipAdded.shipId, rosterShipAdded.position);
    RosterData memory updatedRosterData = RosterAddShipLogic.mutate(rosterShipAdded, rosterData);
    Roster.set(playerId, sequenceNumber, updatedRosterData);
  }

}
