// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

library RosterSequenceNumber {
  uint32 constant UNASSIGNED_SHIPS = 0;
  uint32 constant FIRST = 1;
  uint32 constant SECOND = 2;
  uint32 constant THIRD = 3;
  uint32 constant FOURTH = 4;

  function isValid(uint32 v) internal pure returns (bool) {
    return v == UNASSIGNED_SHIPS || v == FIRST || v == SECOND || v == THIRD || v == FOURTH;
  }

  function allValidValues() internal pure returns (uint32[] memory) {
    uint32[] memory values = new uint32[](5);
    values[0] = UNASSIGNED_SHIPS;
    values[1] = FIRST;
    values[2] = SECOND;
    values[3] = THIRD;
    values[4] = FOURTH;
    return values;
  }
}

