// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

library ShipItemType {
  uint8 constant SHIP = 1;
  uint8 constant SHIP_EQUIPMENT = 2;

  function isValid(uint8 v) internal pure returns (bool) {
    return v == SHIP || v == SHIP_EQUIPMENT;
  }

  function allValidValues() internal pure returns (uint8[] memory) {
    uint8[] memory values = new uint8[](2);
    values[0] = SHIP;
    values[1] = SHIP_EQUIPMENT;
    return values;
  }
}

