// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

library SkillType {
  uint8 constant FARMING = 0;
  uint8 constant WOODCUTTING = 1;
  uint8 constant FISHING = 2;
  uint8 constant MINING = 3;
  uint8 constant SMITHING = 4;
  uint8 constant COOKING = 5;
  uint8 constant CRAFTING = 6;
  uint8 constant TOWNSHIP = 7;
  uint8 constant SAILING = 8;
}

