// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemIdQuantityPair } from "./ItemIdQuantityPair.sol";

struct SkillProcessCreated {
  /**
   * @dev The SkillType of the SkillProcessId.
   */
  uint8 skillType;
  /**
   * @dev The PlayerId of the SkillProcessId.
   */
  uint256 playerId;
  /**
   * @dev The SequenceNumber of the SkillProcessId.
   */
  uint8 sequenceNumber;
}

struct ProductionProcessStarted {
  /**
   * @dev The SkillType of the SkillProcessId.
   */
  uint8 skillType;
  /**
   * @dev The PlayerId of the SkillProcessId.
   */
  uint256 playerId;
  /**
   * @dev The SequenceNumber of the SkillProcessId.
   */
  uint8 sequenceNumber;
  uint32 batchSize;
  uint32 itemId;
  uint64 startedAt;
  uint64 creationTime;
  ItemIdQuantityPair[] productionMaterials;
}

struct ProductionProcessCompleted {
  /**
   * @dev The SkillType of the SkillProcessId.
   */
  uint8 skillType;
  /**
   * @dev The PlayerId of the SkillProcessId.
   */
  uint256 playerId;
  /**
   * @dev The SequenceNumber of the SkillProcessId.
   */
  uint8 sequenceNumber;
  uint32 itemId;
  uint64 startedAt;
  uint64 creationTime;
  uint64 endedAt;
  bool successful;
  uint32 quantity;
  uint32 experienceGained;
  uint16 newLevel;
}

struct ShipProductionProcessStarted {
  /**
   * @dev The SkillType of the SkillProcessId.
   */
  uint8 skillType;
  /**
   * @dev The PlayerId of the SkillProcessId.
   */
  uint256 playerId;
  /**
   * @dev The SequenceNumber of the SkillProcessId.
   */
  uint8 sequenceNumber;
  uint32 itemId;
  uint64 startedAt;
  uint64 creationTime;
  ItemIdQuantityPair[] productionMaterials;
}

struct ShipProductionProcessCompleted {
  /**
   * @dev The SkillType of the SkillProcessId.
   */
  uint8 skillType;
  /**
   * @dev The PlayerId of the SkillProcessId.
   */
  uint256 playerId;
  /**
   * @dev The SequenceNumber of the SkillProcessId.
   */
  uint8 sequenceNumber;
  uint32 itemId;
  uint64 startedAt;
  uint64 creationTime;
  uint64 endedAt;
  bool successful;
  uint32 quantity;
  uint32 experienceGained;
  uint16 newLevel;
}

struct CreationProcessStarted {
  /**
   * @dev The SkillType of the SkillProcessId.
   */
  uint8 skillType;
  /**
   * @dev The PlayerId of the SkillProcessId.
   */
  uint256 playerId;
  /**
   * @dev The SequenceNumber of the SkillProcessId.
   */
  uint8 sequenceNumber;
  uint32 batchSize;
  uint32 itemId;
  uint32 resourceCost;
  uint64 startedAt;
  uint64 creationTime;
}

struct CreationProcessCompleted {
  /**
   * @dev The SkillType of the SkillProcessId.
   */
  uint8 skillType;
  /**
   * @dev The PlayerId of the SkillProcessId.
   */
  uint256 playerId;
  /**
   * @dev The SequenceNumber of the SkillProcessId.
   */
  uint8 sequenceNumber;
  uint32 itemId;
  uint64 startedAt;
  uint64 creationTime;
  uint64 endedAt;
  bool successful;
  uint32 quantity;
  uint32 experienceGained;
  uint16 newLevel;
}

