// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { System } from "@latticexyz/world/src/System.sol";
import { SkillProcess, SkillProcessData } from "../codegen/index.sol";
import { SkillProcessCreated, ProductionProcessStarted, ShipProductionProcessStarted, CreationProcessStarted } from "./SkillProcessEvents.sol";
import { SkillProcessCreateLogic } from "./SkillProcessCreateLogic.sol";
import { SkillProcessStartProductionLogic } from "./SkillProcessStartProductionLogic.sol";
import { SkillProcessStartShipProductionLogic } from "./SkillProcessStartShipProductionLogic.sol";
import { SkillProcessStartCreationLogic } from "./SkillProcessStartCreationLogic.sol";
import { ItemIdQuantityPair } from "./ItemIdQuantityPair.sol";

contract SkillProcessFriendSystem is System {
  event SkillProcessCreatedEvent(uint8 indexed skillType, uint256 indexed playerId, uint8 indexed sequenceNumber);

  event ProductionProcessStartedEvent(uint8 indexed skillType, uint256 indexed playerId, uint8 indexed sequenceNumber, uint32 batchSize, uint32 itemId, uint64 energyCost, uint64 startedAt, uint64 creationTime);

  event ShipProductionProcessStartedEvent(uint8 indexed skillType, uint256 indexed playerId, uint8 indexed sequenceNumber, uint32 itemId, uint64 energyCost, uint64 startedAt, uint64 creationTime);

  event CreationProcessStartedEvent(uint8 indexed skillType, uint256 indexed playerId, uint8 indexed sequenceNumber, uint32 batchSize, uint32 itemId, uint64 energyCost, uint32 resourceCost, uint64 startedAt, uint64 creationTime);

  function skillProcessCreate(uint8 skillType, uint256 playerId, uint8 sequenceNumber) public {
    SkillProcessData memory skillProcessData = SkillProcess.get(skillType, playerId, sequenceNumber);
    require(
      skillProcessData.itemId == uint32(0) && skillProcessData.startedAt == uint64(0) && skillProcessData.creationTime == uint64(0) && skillProcessData.completed == false && skillProcessData.endedAt == uint64(0) && skillProcessData.batchSize == uint32(0) && skillProcessData.existing == false,
      "SkillProcess already exists"
    );
    SkillProcessCreated memory skillProcessCreated = SkillProcessCreateLogic.verify(skillType, playerId, sequenceNumber);
    skillProcessCreated.skillType = skillType;
    skillProcessCreated.playerId = playerId;
    skillProcessCreated.sequenceNumber = sequenceNumber;
    emit SkillProcessCreatedEvent(skillProcessCreated.skillType, skillProcessCreated.playerId, skillProcessCreated.sequenceNumber);
    SkillProcessData memory newSkillProcessData = SkillProcessCreateLogic.mutate(skillProcessCreated);
    SkillProcess.set(skillType, playerId, sequenceNumber, newSkillProcessData);
  }

  function skillProcessStartProduction(uint8 skillType, uint256 playerId, uint8 sequenceNumber, uint32 itemId, uint32 batchSize) public {
    SkillProcessData memory skillProcessData = SkillProcess.get(skillType, playerId, sequenceNumber);
    require(
      !(skillProcessData.itemId == uint32(0) && skillProcessData.startedAt == uint64(0) && skillProcessData.creationTime == uint64(0) && skillProcessData.completed == false && skillProcessData.endedAt == uint64(0) && skillProcessData.batchSize == uint32(0) && skillProcessData.existing == false),
      "SkillProcess does not exist"
    );
    ProductionProcessStarted memory productionProcessStarted = SkillProcessStartProductionLogic.verify(skillType, playerId, sequenceNumber, itemId, batchSize, skillProcessData);
    productionProcessStarted.skillType = skillType;
    productionProcessStarted.playerId = playerId;
    productionProcessStarted.sequenceNumber = sequenceNumber;
    emit ProductionProcessStartedEvent(productionProcessStarted.skillType, productionProcessStarted.playerId, productionProcessStarted.sequenceNumber, productionProcessStarted.batchSize, productionProcessStarted.itemId, productionProcessStarted.energyCost, productionProcessStarted.startedAt, productionProcessStarted.creationTime);
    SkillProcessData memory updatedSkillProcessData = SkillProcessStartProductionLogic.mutate(productionProcessStarted, skillProcessData);
    SkillProcess.set(skillType, playerId, sequenceNumber, updatedSkillProcessData);
  }

  function skillProcessStartShipProduction(uint8 skillType, uint256 playerId, uint8 sequenceNumber, uint32 itemId, ItemIdQuantityPair[] memory productionMaterials) public {
    SkillProcessData memory skillProcessData = SkillProcess.get(skillType, playerId, sequenceNumber);
    require(
      !(skillProcessData.itemId == uint32(0) && skillProcessData.startedAt == uint64(0) && skillProcessData.creationTime == uint64(0) && skillProcessData.completed == false && skillProcessData.endedAt == uint64(0) && skillProcessData.batchSize == uint32(0) && skillProcessData.existing == false),
      "SkillProcess does not exist"
    );
    ShipProductionProcessStarted memory shipProductionProcessStarted = SkillProcessStartShipProductionLogic.verify(skillType, playerId, sequenceNumber, itemId, productionMaterials, skillProcessData);
    shipProductionProcessStarted.skillType = skillType;
    shipProductionProcessStarted.playerId = playerId;
    shipProductionProcessStarted.sequenceNumber = sequenceNumber;
    emit ShipProductionProcessStartedEvent(shipProductionProcessStarted.skillType, shipProductionProcessStarted.playerId, shipProductionProcessStarted.sequenceNumber, shipProductionProcessStarted.itemId, shipProductionProcessStarted.energyCost, shipProductionProcessStarted.startedAt, shipProductionProcessStarted.creationTime);
    SkillProcessData memory updatedSkillProcessData = SkillProcessStartShipProductionLogic.mutate(shipProductionProcessStarted, skillProcessData);
    SkillProcess.set(skillType, playerId, sequenceNumber, updatedSkillProcessData);
  }

  function skillProcessStartCreation(uint8 skillType, uint256 playerId, uint8 sequenceNumber, uint32 itemId, uint32 batchSize) public {
    SkillProcessData memory skillProcessData = SkillProcess.get(skillType, playerId, sequenceNumber);
    require(
      !(skillProcessData.itemId == uint32(0) && skillProcessData.startedAt == uint64(0) && skillProcessData.creationTime == uint64(0) && skillProcessData.completed == false && skillProcessData.endedAt == uint64(0) && skillProcessData.batchSize == uint32(0) && skillProcessData.existing == false),
      "SkillProcess does not exist"
    );
    CreationProcessStarted memory creationProcessStarted = SkillProcessStartCreationLogic.verify(skillType, playerId, sequenceNumber, itemId, batchSize, skillProcessData);
    creationProcessStarted.skillType = skillType;
    creationProcessStarted.playerId = playerId;
    creationProcessStarted.sequenceNumber = sequenceNumber;
    emit CreationProcessStartedEvent(creationProcessStarted.skillType, creationProcessStarted.playerId, creationProcessStarted.sequenceNumber, creationProcessStarted.batchSize, creationProcessStarted.itemId, creationProcessStarted.energyCost, creationProcessStarted.resourceCost, creationProcessStarted.startedAt, creationProcessStarted.creationTime);
    SkillProcessData memory updatedSkillProcessData = SkillProcessStartCreationLogic.mutate(creationProcessStarted, skillProcessData);
    SkillProcess.set(skillType, playerId, sequenceNumber, updatedSkillProcessData);
  }

}
