// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

struct TerrainCreated {
  int32 x;
  int32 y;
  string terrainType;
  uint8[] foo;
  bytes bar;
}

struct TerrainUpdated {
  int32 x;
  int32 y;
  string terrainType;
  uint8[] foo;
  bytes bar;
}

