// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

struct TerrainCreated {
  /**
   * @dev The X of the TerrainId.
   */
  uint32 x;
  /**
   * @dev The Y of the TerrainId.
   */
  uint32 y;
  string terrainType;
  uint8[] foo;
  bytes bar;
}

struct TerrainUpdated {
  /**
   * @dev The X of the TerrainId.
   */
  uint32 x;
  /**
   * @dev The Y of the TerrainId.
   */
  uint32 y;
  string terrainType;
  uint8[] foo;
  bytes bar;
}

