// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Coordinates } from "./Coordinates.sol";
import { Coordinates } from "./Coordinates.sol";

struct TwoRostersLocationUpdateParams {
  Coordinates coordinates;
  uint16 updatedSailSeg;
  Coordinates toRosterCoordinates;
  uint16 toRosterUpdatedSailSeg;
  uint64 updatedAt;
}

