// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Coordinates } from "./Coordinates.sol";

struct UpdateLocationParams {
  Coordinates updatedCoordinates;
  uint16 updatedSailSegment;
  uint64 updatedAt;
}

