// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Module } from "@latticexyz/world/src/Module.sol";
import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { WorldResourceIdInstance } from "@latticexyz/world/src/WorldResourceId.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { RESOURCE_SYSTEM, RESOURCE_NAMESPACE } from "@latticexyz/world/src/worldResourceTypes.sol";

import { AppFriendDelegationControl } from "./AppFriendDelegationControl.sol";

contract AppNamespaceDelegationModule is Module {
  using WorldResourceIdInstance for ResourceId;

  AppFriendDelegationControl private immutable appFriendDelegationControl = new AppFriendDelegationControl();
  bytes14 constant APP_NAMESPACE = bytes14("app");

  ResourceId constant APP_NAMESPACE_ID = ResourceId.wrap(bytes32(abi.encodePacked(RESOURCE_NAMESPACE, APP_NAMESPACE)));
  ResourceId constant APP_NAMESPACE_DELEGATION =
    ResourceId.wrap(bytes32(abi.encodePacked(RESOURCE_SYSTEM, APP_NAMESPACE, bytes16("Delegation"))));

  function installRoot(bytes memory) public {
    IBaseWorld world = IBaseWorld(_world());
    bool success;
    bytes memory returnData;

    (success, returnData) = address(world).delegatecall(
      abi.encodeCall(world.registerSystem, (APP_NAMESPACE_DELEGATION, appFriendDelegationControl, true))
    );
    if (!success) revertWithBytes(returnData);

    (success, returnData) = address(world).delegatecall(
      abi.encodeCall(world.registerNamespaceDelegation, (APP_NAMESPACE_ID, APP_NAMESPACE_DELEGATION, new bytes(0)))
    );
    if (!success) revertWithBytes(returnData);
  }

  function install(bytes memory) public pure {
    revert Module_NonRootInstallNotSupported();
  }
}
